import React from 'react';
import './Slide35.css';

export default function Slide35() {
  return (
    <div className="slide-35"><div className="bg-pattern"></div><div className="grid-lines"></div><div className="content-wrapper"><div className="header"><div className="title-section"><div className="title-icon"><i className="fas fa-filter"></i></div><div><div className="main-title">Tunnel de vente - Schéma</div><div className="subtitle">Optimisation du parcours client et conversion</div></div></div><div className="badge"><i className="fas fa-chart-line" style={{marginRight: '8px'}}></i>3 Niveaux </div></div><div className="main-content"><div className="left-panel"><div className="funnel-container"><div className="funnel-header"><div className="funnel-title"><i className="fas fa-project-diagram" style={{color: '#3B82F6'}}></i>Structure du funnel de conversion </div><div style={{color: '#94a3b8', fontSize: '15px'}}><i className="fas fa-clock" style={{marginRight: '6px'}}></i>Durée moyenne: 45 jours </div></div><div className="funnel-body"><div className="funnel-visual"><div className="funnel-stage tofu"><div className="stage-info"><div className="stage-icon blue"><i className="fas fa-users"></i></div><div className="stage-text"><div className="stage-title">TOFU - Top of Funnel</div><div className="stage-desc">Sensibilisation et acquisition</div></div></div><div className="stage-stats"><div className="stat-item"><div className="stat-value">10,
000</div><div className="stat-label">Visiteurs</div></div><div className="stat-item"><div className="stat-value">25%</div><div className="stat-label">Conversion</div></div></div></div><div className="funnel-stage mofu"><div className="stage-info"><div className="stage-icon green"><i className="fas fa-heart"></i></div><div className="stage-text"><div className="stage-title">MOFU - Middle of Funnel</div><div className="stage-desc">Engagement et considération</div></div></div><div className="stage-stats"><div className="stat-item"><div className="stat-value">2,
500</div><div className="stat-label">Leads</div></div><div className="stat-item"><div className="stat-value">40%</div><div className="stat-label">Conversion</div></div></div></div><div className="funnel-stage bofu"><div className="stage-info"><div className="stage-icon orange"><i className="fas fa-shopping-cart"></i></div><div className="stage-text"><div className="stage-title">BOFU - Bottom of Funnel</div><div className="stage-desc">Conversion et vente</div></div></div><div className="stage-stats"><div className="stat-item"><div className="stat-value">1,
000</div><div className="stat-label">Clients</div></div><div className="stat-item"><div className="stat-value">60%</div><div className="stat-label">Conversion</div></div></div></div></div><div className="funnel-metrics"><div className="metric-card"><div className="metric-header"><div className="metric-icon blue"><i className="fas fa-eye"></i></div><div className="metric-title">Taux d'ouverture</div>
 </div><div className="metric-value"><span className="value-number">42%</span><span className="value-unit">avg</span></div></div><div className="metric-card"><div className="metric-header"><div className="metric-icon green"><i className="fas fa-mouse-pointer"></i></div><div className="metric-title">Taux de clic</div></div><div className="metric-value"><span className="value-number">8.5%</span><span className="value-unit">avg</span></div></div><div className="metric-card"><div className="metric-header"><div className="metric-icon orange"><i className="fas fa-shopping-cart"></i></div><div className="metric-title">Panier moyen</div></div><div className="metric-value"><span className="value-number">€85</span><span className="value-unit">avg</span></div></div></div></div></div></div><div className="right-panel"><div className="offers-grid"><div className="offer-card"><div className="offer-header"><div className="offer-icon blue"><i className="fas fa-gift"></i></div><div className="offer-title">Lead Magnet</div></div><div className="offer-desc">Guide gratuit,
ebook,
template</div><div className="offer-stats"><div className="offer-stat"><i className="fas fa-download stat-icon green"></i><span>85% download</span></div><div className="offer-stat"><i className="fas fa-user stat-icon green"></i><span>1,
200 leads</span></div></div></div><div className="offer-card"><div className="offer-header"><div className="offer-icon green"><i className="fas fa-tag"></i></div><div className="offer-title">Tripwire</div></div><div className="offer-desc">Offre à faible prix (€7-€27)</div><div className="offer-stats"><div className="offer-stat"><i className="fas fa-shopping-cart stat-icon green"></i><span>45% conversion</span></div><div className="offer-stat"><i className="fas fa-dollar-sign stat-icon green"></i><span>€19 avg</span></div></div></div><div className="offer-card"><div className="offer-header"><div className="offer-icon orange"><i className="fas fa-box"></i></div><div className="offer-title">Core Offer</div></div><div className="offer-desc">Produit/service principal</div><div className="offer-stats"><div className="offer-stat"><i className="fas fa-check stat-icon green"></i><span>32% conversion</span></div><div className="offer-stat"><i className="fas fa-dollar-sign stat-icon green"></i><span>€297 avg</span></div></div></div><div className="offer-card"><div className="offer-header"><div className="offer-icon purple"><i className="fas fa-arrow-up"></i></div><div className="offer-title">Upsell</div></div><div className="offer-desc">Offre complémentaire</div><div className="offer-stats"><div className="offer-stat"><i className="fas fa-plus stat-icon green"></i><span>25% uptake</span></div><div className="offer-stat"><i className="fas fa-dollar-sign stat-icon green"></i><span>€147 avg</span></div></div></div></div></div></div><div className="bottom-section"><div className="progress-info"><div>Progression: <span style={{color: 'white', fontWeight: 700}}>78%</span></div><div className="progress-bar"><div className="progress-fill" style={{width: '78%'}}></div></div><div style={{color: '#64748b', fontSize: '14px'}}>Dernière mise à jour: Aujourd'hui</div>
 </div><div className="action-buttons"><button className="action-btn secondary"><i className="fas fa-download"></i>Exporter</button><button className="action-btn primary"><i className="fas fa-play"></i>Optimiser</button></div></div></div></div>
  );
}
