import React from 'react';
import './Slide29.css';

export default function Slide29() {
  return (
    <div className="slide-29"><div className="bg-pattern"></div><div className="grid-lines"></div><div className="content-wrapper"><div className="header"><div className="title-section"><div className="title-icon"><i className="fas fa-users"></i></div><div><div className="main-title">Engagement &amp;
Community Management</div><div className="subtitle">Stratégies pour engager et fidéliser votre communauté</div></div></div><div className="badge"><i className="fas fa-heart" style={{marginRight: '8px'}}></i>Engagement </div></div><div className="content-grid"><div className="section-card"><div className="section-header"><div className="section-icon blue"><i className="fas fa-comments"></i></div><div className="section-title">Lignes d'Engagement</div>
 </div><div className="grid-2"><div className="item-card"><div className="item-icon blue"><i className="fas fa-reply"></i></div><div className="item-content"><div className="item-title">Réponses en 24h</div><div className="item-desc">Répondre à tous les commentaires et messages dans les 24h</div></div></div><div className="item-card"><div className="item-icon green"><i className="fas fa-heart"></i></div><div className="item-content"><div className="item-title">Interactions actives</div><div className="item-desc">Aimer,
commenter et partager le contenu des abonnés</div></div></div><div className="item-card"><div className="item-icon orange"><i className="fas fa-bell"></i></div><div className="item-content"><div className="item-title">Notifications</div><div className="item-desc">Activer les alertes pour mentions et messages</div></div></div><div className="item-card"><div className="item-icon purple"><i className="fas fa-hashtag"></i></div><div className="item-content"><div className="item-title">Hashtags</div><div className="item-desc">Utiliser les hashtags pertinents pour la visibilité</div></div></div></div></div><div className="section-card"><div className="section-header"><div className="section-icon green"><i className="fas fa-chart-line"></i></div><div className="section-title">Social Listening</div></div><div className="item-card" style={{marginBottom: 0}}><div className="item-icon blue"><i className="fas fa-search"></i></div><div className="item-content"><div className="item-title">Surveillance des mentions</div><div className="item-desc">Suivre les mentions de la marque,
produits et concurrents sur tous les canaux</div></div></div><div className="stats-row"><div className="stat-item"><div className="stat-number" style={{color: '#3B82F6'}}>85%</div><div className="stat-label">Sentiment</div></div><div className="stat-item"><div className="stat-number" style={{color: '#10B981'}}>2.3K</div><div className="stat-label">Mentions/mois</div></div><div className="stat-item"><div className="stat-number" style={{color: '#F97316'}}>94%</div><div className="stat-label">Réponse</div></div></div></div></div><div className="bottom-section"><div className="bottom-card"><div className="bottom-header"><div className="bottom-icon orange"><i className="fas fa-users"></i></div><div className="bottom-title">UGC &amp;
Ambassadeurs</div></div><div className="checklist"><div className="check-item"><div className="check-icon" style={{background: '#10B981'}}><i className="fas fa-check"></i></div><div className="check-text">Encourager le contenu généré par les utilisateurs</div></div><div className="check-item"><div className="check-icon" style={{background: '#3B82F6'}}><i className="fas fa-check"></i></div><div className="check-text">Identifier et récompenser les ambassadeurs</div></div><div className="check-item"><div className="check-icon" style={{background: '#F97316'}}><i className="fas fa-check"></i></div><div className="check-text">Partager les témoignages clients</div></div></div></div><div className="bottom-card"><div className="bottom-header"><div className="bottom-icon purple"><i className="fas fa-gamepad"></i></div><div className="bottom-title">Jeux &amp;

Sondages</div></div><div className="checklist"><div className="check-item"><div className="check-icon" style={{background: '#8B5CF6'}}><i className="fas fa-check"></i></div><div className="check-text">Organiser des concours et giveaways</div></div><div className="check-item"><div className="check-icon" style={{background: '#10B981'}}><i className="fas fa-check"></i></div><div className="check-text">Créer des sondages interactifs</div></div><div className="check-item"><div className="check-icon" style={{background: '#3B82F6'}}><i className="fas fa-check"></i></div><div className="check-text">Gamifier l'engagement</div>
 </div></div></div><div className="bottom-card"><div className="bottom-header"><div className="bottom-icon blue"><i className="fas fa-shield-alt"></i></div><div className="bottom-title">Modération</div></div><div className="checklist"><div className="check-item"><div className="check-icon" style={{background: '#F97316'}}><i className="fas fa-check"></i></div><div className="check-text">Établir une charte de modération</div></div><div className="check-item"><div className="check-icon" style={{background: '#10B981'}}><i className="fas fa-check"></i></div><div className="check-text">Réagir rapidement aux crises</div></div><div className="check-item"><div className="check-icon" style={{background: '#3B82F6'}}><i className="fas fa-check"></i></div><div className="check-text">Former les modérateurs</div></div></div></div></div></div></div>
  );
}
