import React from 'react';
import './Slide31.css';

export default function Slide31() {
  return (
    <div className="slide-31"><div className="bg-pattern"></div><div className="grid-lines"></div><div className="content-wrapper"><div className="header"><div className="title-section"><div className="title-icon"><i className="fab fa-google"></i></div><div><div className="main-title">Google Ads - Types &amp;
Optimisation</div><div className="subtitle">Stratégies de campagnes et optimisation des performances</div></div></div><div className="badge"><i className="fas fa-chart-line" style={{marginRight: '8px'}}></i>6 Types </div></div><div className="main-content"><div className="campaign-structure-grid"><div className="left-panel"><div className="campaign-card" style={{flex: 1.4}}><div className="card-header"><div className="card-title"><div className="card-icon blue"><i className="fas fa-ad"></i></div>Types de campagnes Google Ads </div><div style={{color: '#94a3b8', fontSize: '14px'}}><i className="fas fa-cog" style={{marginRight: '6px'}}></i>Optimisation </div></div><div className="ad-types-grid"><div className="ad-type-card"><div className="ad-type-header"><div className="ad-type-icon blue"><i className="fas fa-search"></i></div><div className="ad-type-title">Search</div></div><div className="ad-type-desc">Annonces textuelles sur les résultats de recherche Google</div></div><div className="ad-type-card"><div className="ad-type-header"><div className="ad-type-icon green"><i className="fas fa-shopping-cart"></i></div><div className="ad-type-title">Shopping</div></div><div className="ad-type-desc">Annonces produits avec images et prix</div></div><div className="ad-type-card"><div className="ad-type-header"><div className="ad-type-icon orange"><i className="fas fa-video"></i></div><div className="ad-type-title">Video</div></div><div className="ad-type-desc">Annonces vidéo sur YouTube</div></div><div className="ad-type-card"><div className="ad-type-header"><div className="ad-type-icon purple"><i className="fas fa-image"></i></div><div className="ad-type-title">Display</div></div><div className="ad-type-desc">Bannières sur le réseau Display</div></div><div className="ad-type-card"><div className="ad-type-header"><div className="ad-type-icon blue"><i className="fas fa-sync-alt"></i></div><div className="ad-type-title">Remarketing</div></div><div className="ad-type-desc">Reciblage des visiteurs</div></div><div className="ad-type-card"><div className="ad-type-header"><div className="ad-type-icon green"><i className="fas fa-bullseye"></i></div><div className="ad-type-title">PMax</div></div><div className="ad-type-desc">Performance Max (tous canaux)</div></div></div><div className="kpi-tags"><div className="kpi-tag green"><i className="fas fa-check"></i>QS: 8.5/10</div><div className="kpi-tag orange"><i className="fas fa-chart-line"></i>CPC: €1.20</div><div className="kpi-tag blue"><i className="fas fa-eye"></i>CTR: 4.2%</div></div></div><div className="campaign-card" style={{flex: 1}}><div className="card-header"><div className="card-title"><div className="card-icon green"><i className="fas fa-cogs"></i></div>Optimisation &amp;
Tests </div></div><div className="optimization-section"><div className="optimization-item"><div className="optimization-info"><div className="optimization-icon blue"><i className="fas fa-key"></i></div><div className="optimization-text">Mots-clés</div></div><div className="optimization-value">1,
245 actifs</div></div><div className="optimization-item"><div className="optimization-info"><div className="optimization-icon green"><i className="fas fa-ban"></i></div><div className="optimization-text">Négatifs</div></div><div className="optimization-value">156 ajoutés</div></div><div className="optimization-item"><div className="optimization-info"><div className="optimization-icon orange"><i className="fas fa-expand"></i></div><div className="optimization-text">Extensions</div></div><div className="optimization-value">8 actives</div></div></div></div></div><div className="right-panel"><div className="campaign-card" style={{flex: 1.2}}><div className="card-header"><div className="card-title"><div className="card-icon orange"><i className="fas fa-chart-bar"></i></div>KPIs &amp;

Métriques </div></div><div className="metrics-grid"><div className="metric-card"><div className="metric-header"><div className="metric-icon blue"><i className="fas fa-dollar-sign"></i></div><div className="metric-title">CPC</div></div><div className="metric-value"><span className="value-number">€1.20</span><span className="value-unit">/clic</span></div><div className="status-bar"><div className="status-dot green"></div><div className="status-text">-15% vs hier</div></div></div><div className="metric-card"><div className="metric-header"><div className="metric-icon green"><i className="fas fa-chart-line"></i></div><div className="metric-title">ROAS</div></div><div className="metric-value"><span className="value-number">4.2x</span><span className="value-unit">return</span></div><div className="status-bar"><div className="status-dot green"></div><div className="status-text">+8% vs hier</div></div></div><div className="metric-card"><div className="metric-header"><div className="metric-icon orange"><i className="fas fa-eye"></i></div><div className="metric-title">CTR</div></div><div className="metric-value"><span className="value-number">4.2%</span><span className="value-unit">clics</span></div><div className="status-bar"><div className="status-dot green"></div><div className="status-text">+12% vs hier</div></div></div><div className="metric-card"><div className="metric-header"><div className="metric-icon purple"><i className="fas fa-percentage"></i></div><div className="metric-title">Conv.</div></div><div className="metric-value"><span className="value-number">3.8%</span><span className="value-unit">rate</span></div><div className="status-bar"><div className="status-dot orange"></div><div className="status-text">-3% vs hier</div></div></div></div></div><div className="campaign-card" style={{flex: 1}}><div className="card-header"><div className="card-title"><div className="card-icon purple"><i className="fas fa-cogs"></i></div>Configuration </div></div><div className="optimization-section"><div className="optimization-item"><div className="optimization-info"><div className="optimization-icon blue"><i className="fas fa-code"></i></div><div className="optimization-text">Conversion Tracking</div></div><div className="optimization-value">Actif</div></div><div className="optimization-item"><div className="optimization-info"><div className="optimization-icon green"><i className="fas fa-mobile-alt"></i></div><div className="optimization-text">Mobile Optimized</div></div><div className="optimization-value">Oui</div></div></div></div></div></div></div><div className="bottom-section"><div className="progress-info"><div>Progression: <span style={{color: 'white', fontWeight: 700}}>92%</span></div><div className="progress-bar"><div className="progress-fill" style={{width: '92%'}}></div></div><div style={{color: '#64748b', fontSize: '13px'}}>Dernière mise à jour: Aujourd'hui</div>
 </div><div className="action-buttons"><button className="action-btn secondary"><i className="fas fa-download"></i>Exporter</button><button className="action-btn primary"><i className="fas fa-play"></i>Lancer</button></div></div></div></div>
  );
}
