import React from 'react';
import './Slide26.css';

export default function Slide26() {
  return (
    <div className="slide-26"><div className="bg-pattern"></div><div className="grid-lines"></div><div className="content-wrapper"><div className="header"><div className="title-section"><div className="title-icon"><i className="fas fa-layer-group"></i></div><div><div className="main-title">Stack Technologique</div><div className="subtitle">Outils et technologies essentiels pour le marketing digital</div></div></div><div className="badge"><i className="fas fa-tools" style={{marginRight: '8px'}}></i>15 outils </div></div><div className="main-content"><div className="table-container"><div className="table-header"><div className="table-title">Liste complète des outils</div><div className="table-actions"><button className="action-btn secondary"><i className="fas fa-filter"></i>Filtrer</button><button className="action-btn primary"><i className="fas fa-plus"></i>Ajouter</button></div></div><div className="tools-table"><div className="table-row header"><div className="table-cell header-cell">Catégorie</div><div className="table-cell header-cell">Outil</div><div className="table-cell header-cell">Usage</div><div className="table-cell header-cell">Coût</div><div className="table-cell header-cell">Priorité</div><div className="table-cell header-cell">Statut</div></div><div className="table-row"><div className="table-cell"><div className="category-badge seo"><i className="fas fa-search"></i>SEO</div></div><div className="table-cell"><div className="tool-name"><div className="tool-icon" style={{background: 'rgba(16, 185, 129, 0.2)', color: '#10B981'}}><i className="fas fa-search"></i></div><span className="tool-name-text">SEMrush</span></div></div><div className="table-cell"><div className="usage-text">Analyse SEO,
mots-clés,
backlinks</div></div><div className="table-cell"><div className="cost-badge premium">€119/mois</div></div><div className="table-cell"><div className="priority-indicator"><div className="priority-dot high"></div><span className="priority-text">Haute</span></div></div><div className="table-cell"><span style={{color: '#10B981'}}><i className="fas fa-check-circle"></i>Actif</span></div></div><div className="table-row"><div className="table-cell"><div className="category-badge analytics"><i className="fas fa-chart-line"></i>Analytics</div></div><div className="table-cell"><div className="tool-name"><div className="tool-icon" style={{background: 'rgba(37, 99, 235, 0.2)', color: '#3B82F6'}}><i className="fas fa-chart-line"></i></div><span className="tool-name-text">Google Analytics 4</span></div></div><div className="table-cell"><div className="usage-text">Tracking,
rapports,
analyses</div></div><div className="table-cell"><div className="cost-badge free">Gratuit</div></div><div className="table-cell"><div className="priority-indicator"><div className="priority-dot high"></div><span className="priority-text">Haute</span></div></div><div className="table-cell"><span style={{color: '#10B981'}}><i className="fas fa-check-circle"></i>Actif</span></div></div><div className="table-row"><div className="table-cell"><div className="category-badge ads"><i className="fas fa-bullhorn"></i>Ads</div></div><div className="table-cell"><div className="tool-name"><div className="tool-icon" style={{background: 'rgba(249, 115, 22, 0.2)', color: '#F97316'}}><i className="fas fa-bullhorn"></i></div><span className="tool-name-text">Google Ads</span></div></div><div className="table-cell"><div className="usage-text">Campagnes PPC,
remarketing</div></div><div className="table-cell"><div className="cost-badge paid">Variable</div></div><div className="table-cell"><div className="priority-indicator"><div className="priority-dot high"></div><span className="priority-text">Haute</span></div></div><div className="table-cell"><span style={{color: '#10B981'}}><i className="fas fa-check-circle"></i>Actif</span></div></div><div className="table-row"><div className="table-cell"><div className="category-badge social"><i className="fas fa-share-alt"></i>Social</div></div><div className="table-cell"><div className="tool-name"><div className="tool-icon" style={{background: 'rgba(139, 92, 246, 0.2)', color: '#8B5CF6'}}><i className="fas fa-share-alt"></i></div><span className="tool-name-text">Hootsuite</span></div></div><div className="table-cell"><div className="usage-text">Gestion réseaux sociaux</div></div><div className="table-cell"><div className="cost-badge premium">€99/mois</div></div><div className="table-cell"><div className="priority-indicator"><div className="priority-dot medium"></div><span className="priority-text">Moyenne</span></div></div><div className="table-cell"><span style={{color: '#F97316'}}><i className="fas fa-clock"></i>En test</span></div></div><div className="table-row"><div className="table-cell"><div className="category-badge email"><i className="fas fa-envelope"></i>Email</div></div><div className="table-cell"><div className="tool-name"><div className="tool-icon" style={{background: 'rgba(236, 72, 153, 0.2)', color: '#EC4899'}}><i className="fas fa-envelope"></i></div><span className="tool-name-text">Mailchimp</span></div></div><div className="table-cell"><div className="usage-text">Email marketing,
automation</div></div><div className="table-cell"><div className="cost-badge paid">€13/mois</div></div><div className="table-cell"><div className="priority-indicator"><div className="priority-dot medium"></div><span className="priority-text">Moyenne</span></div></div><div className="table-cell"><span style={{color: '#10B981'}}><i className="fas fa-check-circle"></i>Actif</span></div></div><div className="table-row"><div className="table-cell"><div className="category-badge automation"><i className="fas fa-robot"></i>Auto</div></div><div className="table-cell"><div className="tool-name"><div className="tool-icon" style={{background: 'rgba(6, 182, 212, 0.2)', color: '#06B6D4'}}><i className="fas fa-robot"></i></div><span className="tool-name-text">Zapier</span></div></div><div className="table-cell"><div className="usage-text">Automatisation workflows</div></div><div className="table-cell"><div className="cost-badge paid">€20/mois</div></div><div className="table-cell"><div className="priority-indicator"><div className="priority-dot medium"></div><span className="priority-text">Moyenne</span></div></div><div className="table-cell"><span style={{color: '#10B981'}}><i className="fas fa-check-circle"></i>Actif</span></div></div></div></div><div className="bottom-section"><div style={{color: '#94a3b8', fontSize: '14px'}}>Total: 15 outils actifs | 8 gratuits | 7 payants </div><div className="stats-grid"><div className="stat-item"><i className="fas fa-check-circle" style={{color: '#10B981'}}></i><span className="stat-value">12/15</span><span style={{color: '#94a3b8'}}>actifs</span></div><div className="stat-item"><i className="fas fa-euro-sign" style={{color: '#F97316'}}></i><span className="stat-value">€312</span><span style={{color: '#94a3b8'}}>/mois</span></div></div></div></div></div></div>
  );
}
