import React from 'react';
import './Slide32.css';

export default function Slide32() {
  return (
    <div className="slide-32"><div className="bg-pattern"></div><div className="grid-lines"></div><div className="content-wrapper"><div className="header"><div className="title-section"><div className="title-icon"><i className="fas fa-calculator"></i></div><div><div className="main-title">Budget publicitaire - Répartition</div><div className="subtitle">Stratégie Test/Scale (70-20-10) &amp;
Optimisation des canaux</div></div></div><div className="badge"><i className="fas fa-chart-pie" style={{marginRight: '8px'}}></i>6 canaux </div></div><div className="main-content"><div className="table-container"><div className="table-header"><div className="table-title">Répartition du budget par canal</div><div className="table-actions"><button className="action-btn secondary"><i className="fas fa-filter"></i>Filtrer</button><button className="action-btn primary"><i className="fas fa-plus"></i>Ajouter</button></div></div><div className="smart-table"><div className="table-row header"><div className="table-cell header-cell">Canal</div><div className="table-cell header-cell">Objectif</div><div className="table-cell header-cell">% Budget</div><div className="table-cell header-cell">KPI Cible</div><div className="table-cell header-cell">CAC</div><div className="table-cell header-cell">ROAS</div></div><div className="table-row"><div className="table-cell"><div className="objective-cell"><div className="objective-title">Google Ads (Search)</div><div className="objective-desc">Acquisition de leads qualifiés</div></div></div><div className="table-cell"><span className="kpi-badge green">Acquisition</span></div><div className="table-cell"><div className="target-value">35%</div><div className="progress-bar"><div className="progress-fill green" style={{width: '75%'}}></div></div></div><div className="table-cell"><div className="kpi-badge blue">CPA &lt;
25€</div></div><div className="table-cell" style={{color: 'white', fontWeight: 600}}>18€</div><div className="table-cell" style={{color: 'white', fontWeight: 600}}>4.2x</div></div><div className="table-row"><div className="table-cell"><div className="objective-cell"><div className="objective-title">Facebook Ads</div><div className="objective-desc">Brand awareness &amp;
engagement</div></div></div><div className="table-cell"><span className="kpi-badge blue">Awareness</span></div><div className="table-cell"><div className="target-value">25%</div><div className="progress-bar"><div className="progress-fill blue" style={{width: '60%'}}></div></div></div><div className="table-cell"><div className="kpi-badge orange">CPM &lt;
8€</div></div><div className="table-cell" style={{color: 'white', fontWeight: 600}}>12€</div><div className="table-cell" style={{color: 'white', fontWeight: 600}}>3.8x</div></div><div className="table-row"><div className="table-cell"><div className="objective-cell"><div className="objective-title">LinkedIn Ads</div><div className="objective-desc">B2B lead generation</div></div></div><div className="table-cell"><span className="kpi-badge purple">B2B</span></div><div className="table-cell"><div className="target-value">20%</div><div className="progress-bar"><div className="progress-fill orange" style={{width: '45%'}}></div></div></div><div className="table-cell"><div className="kpi-badge green">CPL &lt;
45€</div></div><div className="table-cell" style={{color: 'white', fontWeight: 600}}>38€</div><div className="table-cell" style={{color: 'white', fontWeight: 600}}>2.9x</div></div><div className="table-row"><div className="table-cell"><div className="objective-cell"><div className="objective-title">YouTube Ads</div><div className="objective-desc">Video marketing</div></div></div><div className="table-cell"><span className="kpi-badge orange">Video</span></div><div className="table-cell"><div className="target-value">15%</div><div className="progress-bar"><div className="progress-fill green" style={{width: '30%'}}></div></div></div><div className="table-cell"><div className="kpi-badge blue">CPV &lt;
0.05€</div></div><div className="table-cell" style={{color: 'white', fontWeight: 600}}>8€</div><div className="table-cell" style={{color: 'white', fontWeight: 600}}>3.2x</div></div><div className="table-row" style={{borderBottom: 'none'}}><div className="table-cell"><div className="objective-cell"><div className="objective-title">TikTok Ads</div><div className="objective-desc">Gen Z engagement</div></div></div><div className="table-cell"><span className="kpi-badge green">Viral</span></div><div className="table-cell"><div className="target-value">5%</div><div className="progress-bar"><div className="progress-fill blue" style={{width: '20%'}}></div></div></div><div className="table-cell"><div className="kpi-badge orange">CPM &lt;
5€</div></div><div className="table-cell" style={{color: 'white', fontWeight: 600}}>6€</div><div className="table-cell" style={{color: 'white', fontWeight: 600}}>2.1x</div></div></div></div><div className="bottom-section"><div className="progress-info"><div>Budget total: <span style={{color: 'white', fontWeight: 700, fontSize: '17px'}}>15,
000€/mois</span></div><div className="stats-grid"><div className="stat-item"><i className="fas fa-users" style={{color: '#10B981'}}></i><span className="stat-value">1,
250</span><span>leads/mois</span></div><div className="stat-item"><i className="fas fa-chart-line" style={{color: '#3B82F6'}}></i><span className="stat-value">4.1x</span><span>ROAS moyen</span></div></div></div><div className="budget-summary"><div className="summary-item"><div className="summary-label">CAC moyen</div><div className="summary-value">22€</div></div><div className="summary-item"><div className="summary-label">Conversion</div><div className="summary-value">3.2%</div></div></div></div></div></div></div>
  );
}
