import React from 'react';
import './Slide39.css';

export default function Slide39() {
  return (
    <div className="slide-39"><div className="bg-pattern"></div><div className="grid-lines"></div><div className="content-wrapper"><div className="header"><div className="title-section"><div className="title-icon"><i className="fas fa-briefcase"></i></div><div><div className="main-title">Freelancing vs Agence - Comparatif</div><div className="subtitle">Comparaison des modèles de business et stratégies d'acquisition</div>
 </div></div><div className="badge"><i className="fas fa-balance-scale" style={{marginRight: '8px'}}></i>2 Modèles </div></div><div className="main-content"><div className="comparison-grid"><div className="left-panel"><div className="comparison-card"><div className="card-header"><div className="card-title"><div className="card-icon blue"><i className="fas fa-user"></i></div>Modèle Freelance </div><div className="status-badge active">Actif</div></div><div className="comparison-content"><div className="comparison-row"><div className="comparison-label">Avantages</div><div className="comparison-value"><i className="fas fa-check-circle comparison-icon"></i><span>Flexibilité,
autonomie,
marges élevées</span></div></div><div className="comparison-row"><div className="comparison-label">Limites</div><div className="comparison-value"><i className="fas fa-exclamation-triangle comparison-icon" style={{color: '#F97316'}}></i><span>Charge mentale,
isolation,
instabilité</span></div></div><div className="comparison-row"><div className="comparison-label">Pricing</div><div className="comparison-value"><span>TJ: €400-800 | Forfait: €2k-10k</span></div></div><div className="pricing-grid"><div className="pricing-card"><div className="pricing-header"><div className="pricing-icon blue"><i className="fas fa-euro-sign"></i></div><div className="pricing-title">TJ Moyen</div></div><div className="pricing-value">€600</div><div className="pricing-desc">par jour</div></div><div className="pricing-card"><div className="pricing-header"><div className="pricing-icon green"><i className="fas fa-calendar"></i></div><div className="pricing-title">Forfait</div></div><div className="pricing-value">€5k</div><div className="pricing-desc">projet moyen</div></div><div className="pricing-card"><div className="pricing-header"><div className="pricing-icon orange"><i className="fas fa-percentage"></i></div><div className="pricing-title">Marge</div></div><div className="pricing-value">70%</div><div className="pricing-desc">net</div></div></div></div></div><div className="tools-grid"><div className="tool-item"><div className="tool-icon blue"><i className="fas fa-laptop"></i></div><div className="tool-info"><div className="tool-name">Notion</div><div className="tool-status">Gestion</div></div></div><div className="tool-item"><div className="tool-icon green"><i className="fas fa-calendar"></i></div><div className="tool-info"><div className="tool-name">Calendly</div><div className="tool-status">Rendez-vous</div></div></div><div className="tool-item"><div className="tool-icon orange"><i className="fas fa-file-invoice"></i></div><div className="tool-info"><div className="tool-name">Stripe</div><div className="tool-status">Paiement</div></div></div><div className="tool-item"><div className="tool-icon purple"><i className="fas fa-chart-line"></i></div><div className="tool-info"><div className="tool-name">Toggl</div><div className="tool-status">Tracking</div></div></div></div></div><div className="right-panel"><div className="comparison-card"><div className="card-header"><div className="card-title"><div className="card-icon green"><i className="fas fa-building"></i></div>Modèle Agence </div><div className="status-badge active">Actif</div></div><div className="comparison-content"><div className="comparison-row"><div className="comparison-label">Avantages</div><div className="comparison-value"><i className="fas fa-check-circle comparison-icon"></i><span>Structure,
équipe,
scalabilité</span></div></div><div className="comparison-row"><div className="comparison-label">Limites</div><div className="comparison-value"><i className="fas fa-exclamation-triangle comparison-icon" style={{color: '#F97316'}}></i><span>Coûts élevés,
complexité,
dépendance</span></div></div><div className="comparison-row"><div className="comparison-label">Pricing</div><div className="comparison-value"><span>TJ: €800-1500 | Forfait: €10k-50k</span></div></div><div className="pricing-grid"><div className="pricing-card"><div className="pricing-header"><div className="pricing-icon blue"><i className="fas fa-euro-sign"></i></div><div className="pricing-title">TJ Moyen</div></div><div className="pricing-value">€1200</div><div className="pricing-desc">par jour</div></div><div className="pricing-card"><div className="pricing-header"><div className="pricing-icon green"><i className="fas fa-calendar"></i></div><div className="pricing-title">Forfait</div></div><div className="pricing-value">€25k</div><div className="pricing-desc">projet moyen</div></div><div className="pricing-card"><div className="pricing-header"><div className="pricing-icon orange"><i className="fas fa-percentage"></i></div><div className="pricing-title">Marge</div></div><div className="pricing-value">45%</div><div className="pricing-desc">net</div></div></div></div></div><div className="acquisition-grid"><div className="acquisition-card"><div className="acquisition-header"><div className="acquisition-icon blue"><i className="fas fa-inbox"></i></div><div className="acquisition-title">Inbound</div></div><div className="acquisition-value">65%</div><div className="acquisition-desc">Leads qualifiés</div></div><div className="acquisition-card"><div className="acquisition-header"><div className="acquisition-icon green"><i className="fas fa-bullhorn"></i></div><div className="acquisition-title">Outbound</div></div><div className="acquisition-value">25%</div><div className="acquisition-desc">Prospection active</div></div><div className="acquisition-card"><div className="acquisition-header"><div className="acquisition-icon orange"><i className="fas fa-handshake"></i></div><div className="acquisition-title">Partenariats</div></div><div className="acquisition-value">10%</div><div className="acquisition-desc">Collaborations</div></div></div></div></div></div><div className="bottom-section"><div className="progress-info"><div>Progression: <span style={{color: 'white', fontWeight: 700}}>78%</span></div><div className="progress-bar"><div className="progress-fill" style={{width: '78%'}}></div></div></div><div className="action-buttons"><button className="action-btn secondary"><i className="fas fa-download"></i>Exporter</button><button className="action-btn primary"><i className="fas fa-play"></i>Analyser</button></div></div></div></div>
  );
}
