import React from 'react';
import './Slide21.css';

export default function Slide21() {
  return (
    <div className="slide-21"><div className="bg-pattern"></div><div className="grid-lines"></div><div className="content-wrapper"><div className="header"><div className="title-section"><div className="title-icon"><i className="fas fa-link"></i></div><div><div className="main-title">SEO Off-Page - Stratégies de Backlinks</div><div className="subtitle">Stratégies avancées pour construire des liens de qualité</div></div></div><div className="badge"><i className="fas fa-chart-line" style={{marginRight: '8px'}}></i>6 Stratégies </div></div><div className="main-content"><div className="strategies-grid"><div className="strategy-card digital-pr"><div className="strategy-header"><div className="strategy-icon blue"><i className="fas fa-newspaper"></i></div><div className="strategy-info"><div className="strategy-title">Digital PR</div><div className="strategy-subtitle">Relations presse digitales</div></div></div><div className="strategy-content"><div className="strategy-item"><div className="item-icon blue"><i className="fas fa-bullhorn"></i></div><div className="item-content"><div className="item-title">Création de contenus newsworthy</div><div className="item-desc">Études,
infographies,
données exclusives</div></div><div className="impact-badge high">Haute</div></div><div className="strategy-item"><div className="item-icon blue"><i className="fas fa-handshake"></i></div><div className="item-content"><div className="item-title">Relations avec journalistes</div><div className="item-desc">Networking et outreach</div></div><div className="impact-badge medium">Moyenne</div></div></div></div><div className="strategy-card content"><div className="strategy-header"><div className="strategy-icon green"><i className="fas fa-share-alt"></i></div><div className="strategy-info"><div className="strategy-title">Contenus liables</div><div className="strategy-subtitle">Création de ressources</div></div></div><div className="strategy-content"><div className="strategy-item"><div className="item-icon green"><i className="fas fa-file-alt"></i></div><div className="item-content"><div className="item-title">Guides complets</div><div className="item-desc">Ressources exhaustives et uniques</div></div><div className="impact-badge high">Haute</div></div><div className="strategy-item"><div className="item-icon green"><i className="fas fa-tools"></i></div><div className="item-content"><div className="item-title">Outils gratuits</div><div className="item-desc">Calculatrices,
templates</div></div><div className="impact-badge medium">Moyenne</div></div></div></div><div className="strategy-card guest-post"><div className="strategy-header"><div className="strategy-icon orange"><i className="fas fa-pen-fancy"></i></div><div className="strategy-info"><div className="strategy-title">Guest Posts</div><div className="strategy-subtitle">Contenu invité qualitatif</div></div></div><div className="strategy-content"><div className="strategy-item"><div className="item-icon orange"><i className="fas fa-edit"></i></div><div className="item-content"><div className="item-title">Articles de qualité</div><div className="item-desc">Contenu original et pertinent</div></div><div className="impact-badge high">Haute</div></div><div className="strategy-item"><div className="item-icon orange"><i className="fas fa-blog"></i></div><div className="item-content"><div className="item-title">Blogs de niche</div><div className="item-desc">Sites pertinents et autorisés</div></div><div className="impact-badge medium">Moyenne</div></div></div></div><div className="strategy-card haro"><div className="strategy-header"><div className="strategy-icon purple"><i className="fas fa-question-circle"></i></div><div className="strategy-info"><div className="strategy-title">HARO &amp;

Équivalents</div><div className="strategy-subtitle">Réponses aux journalistes</div></div></div><div className="strategy-content"><div className="strategy-item"><div className="item-icon purple"><i className="fas fa-reply"></i></div><div className="item-content"><div className="item-title">Réponses rapides</div><div className="item-desc">Répondre aux demandes des médias</div></div><div className="impact-badge high">Haute</div></div><div className="strategy-item"><div className="item-icon purple"><i className="fas fa-clock"></i></div><div className="item-content"><div className="item-title">Timing optimal</div><div className="item-desc">Réponse sous 24h</div></div><div className="impact-badge medium">Moyenne</div></div></div></div><div className="strategy-card co-marketing"><div className="strategy-header"><div className="strategy-icon pink"><i className="fas fa-users"></i></div><div className="strategy-info"><div className="strategy-title">Co-marketing</div><div className="strategy-subtitle">Partenariats stratégiques</div></div></div><div className="strategy-content"><div className="strategy-item"><div className="item-icon pink"><i className="fas fa-handshake"></i></div><div className="item-content"><div className="item-title">Collaborations</div><div className="item-desc">Partenariats mutuellement bénéfiques</div></div><div className="impact-badge high">Haute</div></div><div className="strategy-item"><div className="item-icon pink"><i className="fas fa-gift"></i></div><div className="item-content"><div className="item-title">Offres communes</div><div className="item-desc">Promotions conjointes</div></div><div className="impact-badge medium">Moyenne</div></div></div></div><div className="strategy-card local-citation"><div className="strategy-header"><div className="strategy-icon cyan"><i className="fas fa-map-marker-alt"></i></div><div className="strategy-info"><div className="strategy-title">Citations locales</div><div className="strategy-subtitle">Présence locale</div></div></div><div className="strategy-content"><div className="strategy-item"><div className="item-icon cyan"><i className="fas fa-building"></i></div><div className="item-content"><div className="item-title">Annuaires locaux</div><div className="item-desc">Google My Business,
Yelp</div></div><div className="impact-badge high">Haute</div></div><div className="strategy-item"><div className="item-icon cyan"><i className="fas fa-phone"></i></div><div className="item-content"><div className="item-title">NAP cohérent</div><div className="item-desc">Nom,
Adresse,
Téléphone</div></div><div className="impact-badge medium">Moyenne</div></div></div></div></div><div className="tracking-section"><div className="tracking-card"><div className="tracking-header"><div className="tracking-icon blue"><i className="fas fa-shield-alt"></i></div><div className="tracking-title">Toxicité</div></div><div className="tracking-content"><div className="tracking-item"><span className="tracking-label">Score de toxicité</span><span className="tracking-value">12/100</span></div><div className="tracking-item"><span className="tracking-label">Liens toxiques</span><span className="tracking-value">3</span></div></div></div><div className="tracking-card"><div className="tracking-header"><div className="tracking-icon green"><i className="fas fa-anchor"></i></div><div className="tracking-title">Ancres</div></div><div className="tracking-content"><div className="tracking-item"><span className="tracking-label">Ancres optimisées</span><span className="tracking-value">85%</span></div><div className="tracking-item"><span className="tracking-label">Ancres variées</span><span className="tracking-value">15%</span></div></div></div><div className="tracking-card"><div className="tracking-header"><div className="tracking-icon orange"><i className="fas fa-chart-bar"></i></div><div className="tracking-title">Topical Authority</div></div><div className="tracking-content"><div className="tracking-item"><span className="tracking-label">Score thématique</span><span className="tracking-value">78/100</span></div><div className="tracking-item"><span className="tracking-label">Expertise</span><span className="tracking-value">Haute</span></div></div></div></div><div className="bottom-section"><div className="progress-info"><div>Progression: <span style={{color: 'white', fontWeight: 700}}>75%</span></div><div className="progress-bar"><div className="progress-fill" style={{width: '75%'}}></div></div><div style={{color: '#64748b', fontSize: '12px'}}>Dernière mise à jour: Aujourd'hui</div>
 </div><div className="action-buttons"><button className="action-btn secondary"><i className="fas fa-download"></i>Exporter </button><button className="action-btn primary"><i className="fas fa-play"></i>Analyser </button></div></div></div></div></div>
  );
}
