import React from 'react';
import './Slide22.css';

export default function Slide22() {
  return (
    <div className="slide-22"><div className="bg-pattern"></div><div className="grid-lines"></div><div className="content-wrapper"><div className="header"><div className="title-section"><div className="title-icon"><i className="fas fa-search"></i></div><div><div className="main-title">Recherche de mots-clés - Méthodologie</div><div className="subtitle">Processus complet de recherche et d'analyse de mots-clés</div>
 </div></div><div className="badge"><i className="fas fa-key" style={{marginRight: '8px'}}></i>6 Étapes </div></div><div className="main-content"><div className="process-flow"><div className="process-step"><div className="step-number">1</div><div className="step-header"><div className="step-icon blue"><i className="fas fa-seedling"></i></div><div className="step-title">Seeds &amp;
Concurrents</div></div><div className="step-content"><div className="step-item"><div className="step-item-icon blue"><i className="fas fa-search"></i></div><div className="step-item-text">Analyse des seeds</div><div className="step-item-value">50+</div></div><div className="step-item"><div className="step-item-icon green"><i className="fas fa-users"></i></div><div className="step-item-text">Concurrents</div><div className="step-item-value">10</div></div></div></div><i className="fas fa-arrow-right arrow-icon"></i><div className="process-step"><div className="step-number">2</div><div className="step-header"><div className="step-icon green"><i className="fas fa-bullseye"></i></div><div className="step-title">Intentions</div></div><div className="step-content"><div className="step-item"><div className="step-item-icon blue"><i className="fas fa-info"></i></div><div className="step-item-text">Informationnelle</div><div className="step-item-value">40%</div></div><div className="step-item"><div className="step-item-icon green"><i className="fas fa-shopping-cart"></i></div><div className="step-item-text">Transactionnelle</div><div className="step-item-value">35%</div></div></div></div><i className="fas fa-arrow-right arrow-icon"></i><div className="process-step"><div className="step-number">3</div><div className="step-header"><div className="step-icon orange"><i className="fas fa-chart-bar"></i></div><div className="step-title">Volume &amp;

KD</div></div><div className="step-content"><div className="step-item"><div className="step-item-icon orange"><i className="fas fa-eye"></i></div><div className="step-item-text">Volume mensuel</div><div className="step-item-value">10K+</div></div><div className="step-item"><div className="step-item-icon purple"><i className="fas fa-key"></i></div><div className="step-item-text">KD moyen</div><div className="step-item-value">45</div></div></div></div><i className="fas fa-arrow-right arrow-icon"></i><div className="process-step"><div className="step-number">4</div><div className="step-header"><div className="step-icon purple"><i className="fas fa-layer-group"></i></div><div className="step-title">Clustering</div></div><div className="step-content"><div className="step-item"><div className="step-item-icon purple"><i className="fas fa-sitemap"></i></div><div className="step-item-text">Thématiques</div><div className="step-item-value">12</div></div><div className="step-item"><div className="step-item-icon pink"><i className="fas fa-link"></i></div><div className="step-item-text">Mapping</div><div className="step-item-value">100%</div></div></div></div></div><div className="metrics-grid"><div className="metric-card"><div className="metric-header"><div className="metric-icon blue"><i className="fas fa-search"></i></div><div className="metric-title">Mots-clés trouvés</div></div><div className="metric-value"><span className="value-number">2,
847</span><span className="value-unit">mots</span></div><div className="metric-bar"><div className="metric-fill blue" style={{width: '85%'}}></div></div></div><div className="metric-card"><div className="metric-header"><div className="metric-icon green"><i className="fas fa-chart-line"></i></div><div className="metric-title">Volume total</div></div><div className="metric-value"><span className="value-number">1.2M</span><span className="value-unit">/mois</span></div><div className="metric-bar"><div className="metric-fill green" style={{width: '72%'}}></div></div></div><div className="metric-card"><div className="metric-header"><div className="metric-icon orange"><i className="fas fa-trophy"></i></div><div className="metric-title">KD moyen</div></div><div className="metric-value"><span className="value-number">45</span><span className="value-unit">/100</span></div><div className="metric-bar"><div className="metric-fill orange" style={{width: '45%'}}></div></div></div><div className="metric-card"><div className="metric-header"><div className="metric-icon purple"><i className="fas fa-percentage"></i></div><div className="metric-title">Clics potentiels</div></div><div className="metric-value"><span className="value-number">8.5%</span><span className="value-unit">CTR</span></div><div className="metric-bar"><div className="metric-fill purple" style={{width: '65%'}}></div></div></div></div><div className="bottom-section"><div className="progress-info"><div className="progress-bar-container"><span>Progression: <strong style={{color: 'white'}}>78%</strong></span><div className="progress-bar"><div className="progress-fill" style={{width: '78%'}}></div></div></div><div style={{color: '#475569', fontSize: '13px'}}>Dernière mise à jour: Aujourd'hui</div>
 </div><div className="action-buttons"><button className="action-btn secondary"><i className="fas fa-download"></i>Exporter</button><button className="action-btn primary"><i className="fas fa-play"></i>Analyser</button></div></div></div></div></div>
  );
}
